name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
env:
  CI: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: npm i -g pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          # ...yeah, I don't know. Something something compilation order.
          mv runtime/src/extension-preloader.ts ../
          pnpm build
          mv ../extension-preloader.ts runtime/src/
          pnpm build
      - name: Lint
        run: pnpm lint
      - name: Check formatting
        if: runner.os != 'Windows'
        run: pnpm check-fmt
